### ISSUE TITLE
Is there no way to grant com.android.providers.tv.permission.ACCESS_ALL_EPG_DATA permission to non-system apps via ADB to be able to use channels?

### ISSUE THREAD

**Issue by SevastianGit** [nielsvanvelzen/tv-launcher#11]
Well, the title says everything. There are many great custom launchers out there but the only way holding me back from switching to them is the lack of channels which is my most favorite feature. I am curious if it could perhaps be possible to somehow grant this permission to an app via ADB or something like that. Or perhaps maybe some AndroidTVs are possible to root? Or maybe you could somehow install a non-system app as a system app via ADB? Idk.

**Comment by nielsvanvelzen** [comment]
When I looked into this the only solution I could find was to modify the operating system. So no it's not really possible.
