### ISSUE TITLE
Latest build App / Build #907 crashing

### ISSUE THREAD

**Issue by ACR-Jeff** [nielsvanvelzen/tv-launcher#384]
Latest build App / Build #907 crashing
Device: Nvidia Shield 2017 16GB
Android TV: version 9

[logcat.txt](https://github.com/user-attachments/files/17336333/logcat.txt)
Hope this helps solve it.

**Comment by nielsvanvelzen** [comment]
It looks like the app crashes because it's trying to sync the channel information and there is too many items. That bug would've been here since the start of the project. I'll see if I can figure out a way to fix it. Thanks for the report!

**Comment by nielsvanvelzen** [comment]
This should now be fixed. Let me know if this or another crash still occurs!

**Comment by ACR-Jeff** [comment]
Thank you, No crashes so far on my device after your fix. You're welcome.
