### ISSUE TITLE
Database empty

### ISSUE THREAD

**Issue by phongdev20** [nielsvanvelzen/tv-launcher#396]
I downloaded it but there is no database. Can you share them?

**Comment by nielsvanvelzen** [comment]
I'm not sure what you're asking, there is no database supposed to be in the download.

**Comment by phongdev20** [comment]
![Screenshot 2024-11-03 at 21 32 59](https://github.com/user-attachments/assets/290a4363-1f6b-46ba-b109-885084fd809a)

I built it and it just shows a blank screen

**Comment by nielsvanvelzen** [comment]
The home page is empty because you haven't added any app as favorite yet

**Comment by phongdev20** [comment]
Can you guide me through it? Thank you

**Comment by nielsvanvelzen** [comment]
Go to the "All apps" tab, select an app to favorite, long-press the dpad-center button, favorite the item.

**Comment by phongdev20** [comment]
![Screenshot 2024-11-03 at 21 52 46](https://github.com/user-attachments/assets/3b67b2c6-f49a-4b71-8ec9-8890ff973e9e)

I added it but it didn't work

**Comment by nielsvanvelzen** [comment]
You're not even in the app anymore..

**Comment by phongdev20** [comment]
![Screenshot 2024-11-03 at 21 55 12](https://github.com/user-attachments/assets/89a14df1-371b-4377-a26c-0ffe12075097)

**Comment by phongdev20** [comment]
![Screenshot 2024-11-03 at 22 13 23](https://github.com/user-attachments/assets/72223f4d-ce93-4f9a-b168-a289c1f4729a)

When I open the app it still has the same error

**Comment by phongdev20** [comment]
![Screenshot 2024-11-03 at 22 45 27](https://github.com/user-attachments/assets/749a5c8e-ba19-4c40-8f40-1ce08ae469c5)
