### ISSUE TITLE
Hide TV Launcher icon

### ISSUE THREAD

**Issue by 3wichm** [nielsvanvelzen/tv-launcher#7]
Hi,
can you hide apk icon after install TV Launcher?
Tnx
![image](https://user-images.githubusercontent.com/95298775/144454444-b9f4108d-54c8-4cd5-9d0b-3c2d25c8b2b5.png)

**Comment by nielsvanvelzen** [comment]
Preferences to toggle which apps/sources are shown are definitely planned. I just haven't had the time to work on that yet.

**Comment by M7mdZuhair9GamerAlt** [comment]
> Preferences to toggle which apps/sources are shown are definitely planned. I just haven't had the time to work on that yet.

When Will You? Plus i Know you can get wallpapers working,even if it removed a little bit of the 100% Kotlin percentage.

**Comment by nielsvanvelzen** [comment]
You can now choose which apps show up as favorite in  the "home" tab. closing as implemented.
