### ISSUE TITLE
tv launcher apk release.

### ISSUE THREAD

**Issue by Jakeverse** [nielsvanvelzen/tv-launcher#87]
Thanks for making this great app. I wanna change my random local brand's random launcher so it will be very helpful/easy for us to install this launcher on tv.

Literally I have zero knowledge in android studio and don't wanna install it on my slow and storage full laptop. Please consider to release every version in apk format for beginner. Thank you..

**Comment by nielsvanvelzen** [comment]
From #8

> I'll add APK/AAB files to the releases when I have release. But right now this app is still in development and not ready for production use. In the meantime you can build the app manually using Gradle with `gradlew assemble`.

The app is still in development but I've since added continuous integration so you can download the APK from GitHub via this page:
 https://github.com/nielsvanvelzen/tv-launcher/actions/workflows/app-build.yaml?query=branch%3Amaster

Click the item on top and then download the artifacts (click build-artifacts link) to get the APK.

**Comment by Jakeverse** [comment]
thank you so much < 3

**Comment by sorryusernameisalreadytaken** [comment]
> From [#8](https://github.com/nielsvanvelzen/tv-launcher/issues/8)
> 
> > I'll add APK/AAB files to the releases when I have release. But right now this app is still in development and not ready for production use. In the meantime you can build the app manually using Gradle with `gradlew assemble`.
> 
> The app is still in development but I've since added continuous integration so you can download the APK from GitHub via this page: https://github.com/nielsvanvelzen/tv-launcher/actions/workflows/app-build.yaml?query=branch%3Amaster
> 
> Click the item on top and then download the artifacts (click build-artifacts link) to get the APK.

It looks like the zip files are only available for a few days at a time. Could you initiate another build or maybe we can find a more sustainable solution.

I also have problems with the ZIP under AndroidTV. I use the [Bro TV browser](https://play.google.com/store/apps/details?id=com.phlox.tvwebbrowser) quite a lot and a container with the APK in it makes it much more difficult to do an apt update :)
